version: '3'
services:
  backend:
    build: .
    command: uvicorn backend:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  frontend:
    build: .
    command: streamlit run frontend.py --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - backend
